apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oneseismictest
spec:
  environments:
    - name: dev
      build:
        from: radix
    - name: test
      build:
        from: test
  components:
    - name: server
      dockerfileName: Dockerfile
      secrets:
        - VDSSLICE_STORAGE_ACCOUNTS
      ports:
        - name: http
          port: 8080
        - name: metrics
          port: 8081
      publicPort: http
      monitoringConfig:
        portName: metrics
      environmentConfig:
        - environment: dev
          variables:
            VDSSLICE_CACHE_SIZE: 512 # MB
            VDSSLICE_METRICS: true
          monitoring: true
          resources:
            requests:
              memory: "4096Mi"
              cpu: "2000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 3
        - environment: test
          variables:
            VDSSLICE_CACHE_SIZE: 256 # MB
            VDSSLICE_METRICS: true
          monitoring: true
          resources:
            requests:
              memory: "2048Mi"
              cpu: "500m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 3
